#ifndef _KOZOS_EXTINTR_H_INCLUDED_
#define _KOZOS_EXTINTR_H_INCLUDED_

#define EXTINTR_CONSOLE_NUM 2
#define EXTINTR_CONSOLE_SOCKET_PORT 12345
#define EXTINTR_INTERRUPTS_NUM 8

#define EXTINTR_CMD_CONSOLE         'c'

#define EXTINTR_CMD_CONSOLE_USE     'u'
#define EXTINTR_CMD_CONSOLE_ENABLE  'e'
#define EXTINTR_CMD_CONSOLE_DISABLE 'd'
#define EXTINTR_CMD_CONSOLE_WRITE   'w'

#define EXTCONT_CMD_CONTROL_DUMMY   '0'
#define EXTCONT_CMD_CONSOLE_ENABLE  'e'
#define EXTCONT_CMD_CONSOLE_DISABLE 'd'

#endif
