#ifndef _INTERRUPT_H_INCLUDED_
#define _INTERRUPT_H_INCLUDED_

#define VECTOR_NUM 64
#define VECTOR_ADDR ((void *)0xffbf20)
typedef void (*interrupt_handler_t)(int vec);

#define VECTORS ((interrupt_handler_t *)VECTOR_ADDR)

#define ENABLE_INTR  asm volatile ("andc.b #0x3f,ccr")
#define DISABLE_INTR asm volatile ("orc.b #0xc0,ccr")

typedef enum {
  VECTYPE_RESET = 0,
  VECTYPE_RSV1, VECTYPE_RSV2, VECTYPE_RSV3,
  VECTYPE_RSV4, VECTYPE_RSV5, VECTYPE_RSV6,
  VECTYPE_NMI,
  VECTYPE_TRAPA0, VECTYPE_TRAPA1, VECTYPE_TRAPA2, VECTYPE_TRAPA3,
  VECTYPE_IRQ0, VECTYPE_IRQ1, VECTYPE_IRQ2,
  VECTYPE_IRQ3, VECTYPE_IRQ4, VECTYPE_IRQ5,
  VECTYPE_RSV18, VECTYPE_RSV19,
  VECTYPE_WOVI, VECTYPE_CMI, VECTYPE_RSV22, VECTYPE_ADI,
  VECTYPE_IMIA0, VECTYPE_IMIB0, VECTYPE_OVI0, VECTYPE_RSV27,
  VECTYPE_IMIA1, VECTYPE_IMIB1, VECTYPE_OVI1, VECTYPE_RSV31,
  VECTYPE_IMIA2, VECTYPE_IMIB2, VECTYPE_OVI2, VECTYPE_RSV35,
  VECTYPE_CMIA0, VECTYPE_CMIB0, VECTYPE_CMIAB1, VECTYPE_TOVI01,
  VECTYPE_CMIA2, VECTYPE_CMIB2, VECTYPE_CMIAB3, VECTYPE_TOVI23,
  VECTYPE_DEND0A, VECTYPE_DEND0B, VECTYPE_DEND1A, VECTYPE_DEND1B,
  VECTYPE_RSV48, VECTYPE_RSV49, VECTYPE_RSV50, VECTYPE_RSV51,
  VECTYPE_ERI0, VECTYPE_RXI0, VECTYPE_TXI0, VECTYPE_TEI0,
  VECTYPE_ERI1, VECTYPE_RXI1, VECTYPE_TXI1, VECTYPE_TEI1,
  VECTYPE_ERI2, VECTYPE_RXI2, VECTYPE_TXI2, VECTYPE_TEI2,
} interrupt_vectype_t;

int interrupt_init();
int interrupt_sethandler(interrupt_vectype_t vec, interrupt_handler_t handler);
void interrupt(int vec);

#endif
